In [1]:
import numpy as np

In [8]:
a1 = np.array([10, 2, 3, 4, 5])
a2 = np.array([10]*5)
arrs = [a1, a2]
arrs

[array([10,  2,  3,  4,  5]), array([10, 10, 10, 10, 10])]

In [12]:
result = np.zeros(len(a1))
print(result)
for i in range(len(arrs)):
    print(i)
    result = result + arrs[i]
result

[0. 0. 0. 0. 0.]
0
1


array([20., 12., 13., 14., 15.])

In [15]:
result = np.zeros(len(a1))
[np.add(arrs[i], result, out=result) for i in range(len(arrs))]
result

array([20., 12., 13., 14., 15.])